definitions:
  dto.LoginDTO:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  dto.LoginRessponseDTO:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  dto.PagingTaskDto:
    properties:
      keyword:
        type: string
      limit:
        type: integer
      offset:
        type: integer
      status:
        type: string
    type: object
  dto.RegistrationDTO:
    properties:
      fullName:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  dto.UpdateTask:
    properties:
      description:
        example: Updated description
        type: string
      status:
        example: slug-slug
        type: string
      tags:
        example:
        - '[''Bug'''
        - ' ''Urgent'']'
        items:
          type: string
        type: array
      title:
        example: Update title
        type: string
    type: object
  model.Task:
    properties:
      assignedBy:
        $ref: '#/definitions/model.User'
      assignedById:
        type: string
      assignee:
        $ref: '#/definitions/model.User'
      assigneeId:
        type: string
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      slug:
        type: string
      status:
        $ref: '#/definitions/model.TaskStatus'
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      updatedAt:
        type: string
    type: object
  model.TaskStatus:
    enum:
    - TODO
    - IN_PROGRESS
    - REJECTED
    - RESOLVED
    type: string
    x-enum-varnames:
    - Todo
    - InProgress
    - Rejected
    - Resolved
  model.User:
    properties:
      fullName:
        type: string
      id:
        type: string
      password:
        type: string
      title:
        type: string
    type: object
  network.ResCode:
    enum:
    - "7979"
    - "7980"
    - "7981"
    - "7982"
    type: string
    x-enum-varnames:
    - success_code
    - failue_code
    - retry_code
    - invalid_access_token_code
  network.apiError:
    properties:
      code:
        type: integer
      err: {}
      message:
        type: string
    type: object
  network.response:
    properties:
      code:
        $ref: '#/definitions/network.ResCode'
      data: {}
      message:
        type: string
      status:
        type: integer
    required:
    - code
    - data
    - message
    - status
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/authenticate:
    post:
      consumes:
      - application/json
      description: Authenticate account using username and password
      parameters:
      - description: Registration details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginRessponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/network.apiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/network.apiError'
      summary: Authenticate account
      tags:
      - Auth
  /api/v1/auth/registration:
    post:
      consumes:
      - application/json
      description: Create new account using username and password
      parameters:
      - description: Registration details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegistrationDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/network.apiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/network.apiError'
      summary: Create new account
      tags:
      - Auth
  /api/v1/task:
    post:
      consumes:
      - application/json
      description: Create a new task with the input data
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.TaskStatus'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/network.apiError'
      summary: Create a new task
      tags:
      - Task
  /api/v1/task/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a task by its ID
      parameters:
      - description: Task ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success response with number of affected rows
          schema:
            allOf:
            - $ref: '#/definitions/network.response'
            - properties:
                data:
                  type: integer
              type: object
      summary: Delete a task
      tags:
      - Task
    get:
      consumes:
      - application/json
      description: Get a task by its ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Task'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/network.apiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/network.apiError'
      summary: Get a task by ID
      tags:
      - Task
    patch:
      consumes:
      - application/json
      description: Update task fields partially by ID
      parameters:
      - description: Task ID (UUID)
        in: path
        name: id
        required: true
        type: string
      - description: Updated task fields
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateTask'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Task'
      summary: Update a task
      tags:
      - Task
  /api/v1/task/assign:
    post:
      consumes:
      - application/json
      description: Assign task to a user
      parameters:
      - description: Pagination and filter criteria
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.PagingTaskDto'
      produces:
      - application/json
      responses:
        "200":
          description: Success response with paginated tasks
          schema:
            allOf:
            - $ref: '#/definitions/network.response'
            - properties:
                data:
                  $ref: '#/definitions/model.Task'
              type: object
        "400":
          description: Bad request error
          schema:
            $ref: '#/definitions/network.response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/network.response'
      summary: Assign task to a user
      tags:
      - Task
  /api/v1/task/paging:
    post:
      consumes:
      - application/json
      description: Retrieves a paginated list of tasks filtered by title and status
      parameters:
      - description: Pagination and filter criteria
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.PagingTaskDto'
      produces:
      - application/json
      responses:
        "200":
          description: Success response with paginated tasks
          schema:
            allOf:
            - $ref: '#/definitions/network.response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Task'
                  type: array
              type: object
        "400":
          description: Bad request error
          schema:
            $ref: '#/definitions/network.response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/network.response'
      summary: Get paginated list of tasks
      tags:
      - Task
swagger: "2.0"
